version: "5"
services:
  ecoequity:
   image: mongo:latest
   container_name: "ecoequity"
   ports:
    - 27017:27017 
  
  springdockercompose:
   image: springdockercompose:latest
   container_name: "springdockercompose"
   ports:
    - 9095:8085  
   links:
    - ecoequity