server:
  port: 8989
  
eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
         - id: stockdetail
           uri: lb://stockdetail
           predicates:
            - Path=/stocks/**
            
         - id: registration
           uri: lb://registration
           predicates:
            - Path=/users/**
            
         - id: forum
           uri: lb://forum
           predicates:
            - Path=/forum/**      
      
#        - id: user-service
#          uri: lb://User-service
#          predicates:
#            - Path=/user/**
#        
#        - id: contact-service
#          uri: lb://Contact-service
#          predicates:
#            - Path=/contact/**